spring:
  application:
    name: autoever-project-2025

  datasource:
    driver-class-name: org.h2.Driver
    username: sa  #아이디
    password:   #패스워드 (공백)
    generate-unique-name: false
    url: jdbc:h2:mem:testdb  #고정 url

    h2:
      console:
        enabled: true
        path: /h2-console

    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          diarect: org.hibernate.dialect.H2Dialect
          show_sql: true
          format_sql: true
          use_sql_comments: true

  devtools:
    # Auto Restart
    restart:
      enabled: true
      additional-exclude: static/**,public/**

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace  # query의 ?값 추적